"""add name , bio , photo column to user

Revision ID: 09518e9fe2bd
Revises: f9e347e8aed6
Create Date: 2025-08-07 20:34:06.173173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09518e9fe2bd'
down_revision = 'f9e347e8aed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('photo')
        batch_op.drop_column('bio')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
