"""Add image_filename and file_filename to Post

Revision ID: 7e721658a87b
Revises: 09518e9fe2bd
Create Date: 2025-08-08 00:40:33.148951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e721658a87b'
down_revision = '09518e9fe2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ngos')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('file_filename', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_column('content')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('file_filename')
        batch_op.drop_column('image_filename')

    op.create_table('user_ngos',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('ngo_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ngo_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
