"""add sponsers field as comma separated string

Revision ID: f9e347e8aed6
Revises: 21cf16d8d990
Create Date: 2025-08-07 00:10:05.665795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e347e8aed6'
down_revision = '21cf16d8d990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngo_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsors', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngo_event', schema=None) as batch_op:
        batch_op.drop_column('sponsors')

    # ### end Alembic commands ###
